### ISSUE TITLE
moving the folder

### ISSUE THREAD

**Issue by visionm45** [EOSPowerNetwork/vscode-new-eos-contract#2]
After creating a new dev volume for a contract using this tool I can re open the same dev environment by opening the same workspace folder.  So I would expect to be able to move this folder but what I get  when the folder is moved is the following error.  

[2937 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/mouse/EOS Studio/newzcontrct

[3096 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount 
type=volume,src=newzcontrct,dst=/root/eos --mount source=/Users/mouse/EOS Studio/newzcontrct/artifacts,target=/root/eos/build/artifacts,type=bind --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/mouse/EOS Studio/newzcontrct --name=newzcontrct --entrypoint /bin/sh jamesmart/new-eos-contract:latest -c echo Container started

[3096 ms] trap "exit 0" 15

[3096 ms] exec "$@"

[3096 ms] while sleep 1 & wait $!; do :; done -

[3097 ms]     at HR (/Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2183)

[3097 ms]     at tb (/Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2121)

[3097 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

[3097 ms]     at async QR (/Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:2006)

[3097 ms]     at async cb (/Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:3110)

[3097 ms]     at async i_ (/Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:13194)

[3097 ms]     at async n_ (/Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:12950)

[3109 ms] Exit code 1

[3112 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/mouse/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/mouse/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/mouse/EOS Studio/newzcontrct --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/mouse/EOS Studio/newzcontrct --log-level debug --log-format json --config /Users/mouse/EOS Studio/newzcontrct/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true

[3112 ms] Exit code 1

**Comment by James-Mart** [comment]
You won't be able to move the folder on the host machine because the devcontainer.json file relies on the variables: `${localWorkspaceFolder}` and `${localWorkspaceFolderBasename}`.

You have two options, either:
1. Change the variables in the .devcontainer configuration file and hardcode the original values (from the original folder location). You can use [this reference](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) to know what the variable values are.
2. Or push your smart contract code to a github repository, and then use the [VSCode Open EOS Contract](https://github.com/EOSPowerNetwork/vscode-open-eos-contract) tool to open the contract at the new github repo.
